# Generated by Django 4.2.1 on 2023-07-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_catagory_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='catagory',
        ),
    ]
